### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by InasKasem** [InasKasem/web-design-2-independent-project#1]
[Plan your project .pdf](https://github.com/InasKasem/web-design-2-independent-project/files/7542179/Plan.your.project.pdf)

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
| | 0 points | 1 points | 2 points | 3 points | Grade |
| --- | --- | --- | --- | --- | --- |
| **Content inventory** | Incomplete or missing | Rushed & too generic | Specific but obviously lacking research | Specific and appropriate, with good details | 3 |
| **Sitemap** | Incomplete or missing | Has only the pages we’re coding | Lots of important pages missing | Complete, organized and contains all necessary pages | 3 |
| **Homepage wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Page 2 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Page 3 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Logo** | Incomplete or missing | Only works well at one size | Small sizes are inconsistent with large sizes | Cohesive & uniform for all sizes, even if different | 3 |
| **Visual design** | Incomplete or missing | Missing important components or poorly executed | Average, could be more cohesive & considered | Cohesive & appropriate with a good sample of components | 3 |
| **Professionalism** | Rushed & poorly done | Okay | Average, could use more time spent | Clearly demonstrated lots of effort and consideration | 3 |

**Comment by InasKasem** [comment]
[Plan your project .pdf](https://github.com/InasKasem/web-design-2-independent-project/files/7556782/Plan.your.project.pdf)

@thatkidmadrid The updated version

**Comment by thatkidmadrid** [comment]
great, let me know when a good time to meet is for you. I have some free time this afternoon and tomorrow morning if that works for you

**Comment by thatkidmadrid** [comment]
please refer to the rubric to see if you're meeting all the requirements to get full marks!

**Comment by InasKasem** [comment]
Christian, just a question regarding the rubrics. Would you want me to name my code elements and layout? Like nav, cards, links, and layout divs & sections?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thatkidmadrid** [comment]
That could be useful, but not necessary. In your wireframes It should be clear what the main components are, and I should expect to at least see examples of some of your headings. I think what I see is fine, but it would be even better if you had an idea of some of the headings if you put them in the wireframes already.

What i see is missing is the content prioritization using the grey boxes, so you may want to revisit at least one size per page to do that.

Essentially what you want to do is just draw grey boxes over your components and colour code them with different greys (darkest being the highest priority content, and lightest greys being the lesser priority content)

**Comment by InasKasem** [comment]
I editted the wireframes for web-large and added all the main content and images. Although I haven't done this for all sizes, I've already prioritized the content by adding H1, H2, and H3 to these sizes. Hope it works.

[Plan your project .pdf](https://github.com/InasKasem/web-design-2-independent-project/files/7558603/Plan.your.project.pdf)
